### ISSUE TITLE
[feat] Implement OP_ROLL opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#71]
Implement the OP_ROLL opcode using the opcodeRoll [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1349)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by ooochoche** [comment]
@b-j-roberts I can work on this

**Comment by Iwueseiter** [comment]
Hi @b-j-roberts can I work on this?

**Comment by b-j-roberts** [comment]
Sure, I will assign this one to you! Let me know if you have questions. @Iwueseiter

**Comment by b-j-roberts** [comment]
Hey, @Iwueseiter any updates here? I will open this issue for now, but feel free to submit a PR with your work if this is in progress

**Comment by ShantelPeters** [comment]
Hello @b-j-roberts please can I be assigned to this issue

**Comment by Oshioke-Salaki** [comment]
Hello @b-j-roberts i would love to take on this issue
I would solve this issue by:
1. understanding how OP_ROLL works by reading the reference
2. Then i will read on how to add opcodes in shingami
3. Then implement the opcode_roll function in shingami. in order to write the opcode_roll function, would implement the roll_n function in the stack.
4. Then write associated tests with it to make sure that the logic is correct

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts  can I work on this ?
